# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parserUi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.tblParserOutput = QtWidgets.QTableWidget(self.tabMain)
        self.tblParserOutput.setGeometry(QtCore.QRect(30, 30, 790, 491))
        self.tblParserOutput.setObjectName("tblParserOutput")
        self.tblParserOutput.setColumnCount(4)
        self.tblParserOutput.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblParserOutput.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParserOutput.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParserOutput.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParserOutput.setHorizontalHeaderItem(3, item)
        self.tblParserOutput.horizontalHeader().setDefaultSectionSize(197)
        self.btnParse = QtWidgets.QPushButton(self.tabMain)
        self.btnParse.setGeometry(QtCore.QRect(470, 532, 93, 28))
        self.btnParse.setObjectName("btnParse")
        self.cmbLanguageSetting = QtWidgets.QComboBox(self.tabMain)
        self.cmbLanguageSetting.setGeometry(QtCore.QRect(240, 535, 171, 22))
        self.cmbLanguageSetting.setObjectName("cmbLanguageSetting")
        self.cmbLanguageSetting.addItem("")
        self.btnUpdateParser = QtWidgets.QPushButton(self.tabMain)
        self.btnUpdateParser.setGeometry(QtCore.QRect(600, 532, 93, 28))
        self.btnUpdateParser.setObjectName("btnUpdateParser")
        self.tabWidget.addTab(self.tabMain, "")
        self.tabError = QtWidgets.QWidget()
        self.tabError.setObjectName("tabError")
        self.btnUpdateDictionary = QtWidgets.QPushButton(self.tabError)
        self.btnUpdateDictionary.setGeometry(QtCore.QRect(200, 510, 111, 28))
        self.btnUpdateDictionary.setObjectName("btnUpdateDictionary")
        self.tblErrors = QtWidgets.QTableWidget(self.tabError)
        self.tblErrors.setGeometry(QtCore.QRect(40, 40, 771, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblErrors.sizePolicy().hasHeightForWidth())
        self.tblErrors.setSizePolicy(sizePolicy)
        self.tblErrors.setStatusTip("")
        self.tblErrors.setDragDropOverwriteMode(True)
        self.tblErrors.setObjectName("tblErrors")
        self.tblErrors.setColumnCount(3)
        self.tblErrors.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblErrors.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblErrors.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblErrors.setHorizontalHeaderItem(2, item)
        self.tblErrors.horizontalHeader().setDefaultSectionSize(220)
        self.btnUpdateDictionaryAndParse = QtWidgets.QPushButton(self.tabError)
        self.btnUpdateDictionaryAndParse.setGeometry(QtCore.QRect(500, 510, 191, 28))
        self.btnUpdateDictionaryAndParse.setObjectName("btnUpdateDictionaryAndParse")
        self.tabWidget.addTab(self.tabError, "")
        self.tabDictionary = QtWidgets.QWidget()
        self.tabDictionary.setObjectName("tabDictionary")
        self.btnDictionarySearch = QtWidgets.QPushButton(self.tabDictionary)
        self.btnDictionarySearch.setGeometry(QtCore.QRect(470, 500, 93, 28))
        self.btnDictionarySearch.setObjectName("btnDictionarySearch")
        self.tblDictionary = QtWidgets.QTableWidget(self.tabDictionary)
        self.tblDictionary.setGeometry(QtCore.QRect(40, 20, 771, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblDictionary.sizePolicy().hasHeightForWidth())
        self.tblDictionary.setSizePolicy(sizePolicy)
        self.tblDictionary.setStatusTip("")
        self.tblDictionary.setDragDropOverwriteMode(True)
        self.tblDictionary.setObjectName("tblDictionary")
        self.tblDictionary.setColumnCount(3)
        self.tblDictionary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDictionary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDictionary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDictionary.setHorizontalHeaderItem(2, item)
        self.tblDictionary.horizontalHeader().setDefaultSectionSize(257)
        self.btnDictionaryAdd = QtWidgets.QPushButton(self.tabDictionary)
        self.btnDictionaryAdd.setGeometry(QtCore.QRect(720, 500, 93, 28))
        self.btnDictionaryAdd.setObjectName("btnDictionaryAdd")
        self.ltxtDictionaryInput = QtWidgets.QLineEdit(self.tabDictionary)
        self.ltxtDictionaryInput.setGeometry(QtCore.QRect(80, 500, 341, 22))
        self.ltxtDictionaryInput.setText("")
        self.ltxtDictionaryInput.setObjectName("ltxtDictionaryInput")
        self.btnDictionaryUpdate = QtWidgets.QPushButton(self.tabDictionary)
        self.btnDictionaryUpdate.setGeometry(QtCore.QRect(595, 500, 93, 28))
        self.btnDictionaryUpdate.setObjectName("btnDictionaryUpdate")
        self.tabWidget.addTab(self.tabDictionary, "")
        self.btnConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirm.setGeometry(QtCore.QRect(200, 605, 93, 28))
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(580, 605, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LyricParser"))
        item = self.tblParserOutput.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NoteNum"))
        item = self.tblParserOutput.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Lyric"))
        item = self.tblParserOutput.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Word Found"))
        item = self.tblParserOutput.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Syllable"))
        self.btnParse.setText(_translate("MainWindow", "Parse UST"))
        self.cmbLanguageSetting.setItemText(0, _translate("MainWindow", "English VCCV"))
        self.btnUpdateParser.setText(_translate("MainWindow", "Update Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("MainWindow", "Parser"))
        self.btnUpdateDictionary.setText(_translate("MainWindow", "Update Dictionary"))
        item = self.tblErrors.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Word"))
        item = self.tblErrors.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Length"))
        item = self.tblErrors.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Syllables"))
        self.btnUpdateDictionaryAndParse.setText(_translate("MainWindow", "Update Dictionary and Parse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabError), _translate("MainWindow", "Errors"))
        self.btnDictionarySearch.setText(_translate("MainWindow", "Search"))
        item = self.tblDictionary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Word"))
        item = self.tblDictionary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Syllables"))
        item = self.tblDictionary.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Length"))
        self.btnDictionaryAdd.setText(_translate("MainWindow", "Add Word(s)"))
        self.btnDictionaryUpdate.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDictionary), _translate("MainWindow", "Dictionary"))
        self.btnConfirm.setText(_translate("MainWindow", "Confirm"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSettings.setText(_translate("MainWindow", "Close"))

